import { isIP } from "node:net";
import { lookup } from "node:dns/promises";
import { load } from "cheerio";
import { XMLParser } from "fast-xml-parser";

export type SourceMonitorJob = { id: string; title: string; source_type: string; url: string; schedule: string; metadata: Record<string, unknown>; parser_version?: string | null };
export type ExtractedSignal = { title: string; signalType: "job_post" | "internship_post" | "event" | "program" | "fellowship" | "repo_update" | "social_post" | "newsletter_item" | "other"; sourceUrl?: string; canonicalUrl?: string; externalRef?: string; companyName?: string; roleTitle?: string; location?: string; opportunityType?: "job" | "internship" | "event" | "program" | "fellowship" | "competition" | "other"; postedAt?: string; deadlineAt?: string; payload: Record<string, unknown> };

function isPrivateAddress(address: string) { return /^(127\.|10\.|192\.168\.|169\.254\.|0\.|::1$|fc|fd|fe80)/i.test(address) || /^172\.(1[6-9]|2\d|3[01])\./.test(address); }
async function assertPublicUrl(value: string) { const url = new URL(value); if (url.protocol !== "https:") throw new Error("Only HTTPS source URLs are allowed"); if (url.hostname === "localhost" || isIP(url.hostname) && isPrivateAddress(url.hostname)) throw new Error("Private network source URLs are forbidden"); const addresses = await lookup(url.hostname, { all: true }); if (addresses.some(({ address }) => isPrivateAddress(address))) throw new Error("Source resolves to a private network"); return url; }
async function fetchText(url: string) { await assertPublicUrl(url); const response = await fetch(url, { headers: { "user-agent": "CareerOS/0.2 source-monitor", accept: "application/json, application/xml, text/xml, text/html, text/plain" }, redirect: "follow", signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error(`Source returned ${response.status}`); const body = await response.text(); if (body.length > 10_000_000) throw new Error("Source exceeded 10 MB limit"); return { body, contentType: response.headers.get("content-type") ?? "", finalUrl: response.url }; }

function inferType(text: string): ExtractedSignal["signalType"] { const lower = text.toLowerCase(); if (lower.includes("intern")) return "internship_post"; if (lower.includes("fellow")) return "fellowship"; if (lower.includes("event") || lower.includes("fair")) return "event"; return "job_post"; }
function normalizeUrl(value: string, base: string) { try { const url = new URL(value, base); url.hash = ""; ["utm_source", "utm_medium", "utm_campaign", "ref"].forEach((key) => url.searchParams.delete(key)); return url.toString(); } catch { return undefined; } }

function parseGitHubMarkdown(markdown: string, baseUrl: string): ExtractedSignal[] { const results: ExtractedSignal[] = []; const seen = new Set<string>(); const link = /\[([^\]]{3,160})\]\((https?:\/\/[^)\s]+)\)/g; for (const match of markdown.matchAll(link)) { const url = normalizeUrl(match[2], baseUrl); if (!url || seen.has(url) || /github\.com\/(issues|pull|sponsors)/.test(url)) continue; const title = match[1].replace(/[*_`]/g, "").trim(); if (!/(intern|engineer|developer|fellow|program|career|job)/i.test(`${title} ${url}`)) continue; seen.add(url); results.push({ title, roleTitle: title, signalType: inferType(title), opportunityType: inferType(title) === "internship_post" ? "internship" : "job", canonicalUrl: url, sourceUrl: url, externalRef: url, payload: { source: "github_markdown" } }); } return results; }
function parseRss(xml: string, baseUrl: string): ExtractedSignal[] { const parsed = new XMLParser({ ignoreAttributes: false }).parse(xml) as Record<string, unknown>; const root = (parsed.rss as Record<string, unknown> | undefined)?.channel ?? parsed.feed ?? {}; const raw = (root as Record<string, unknown>).item ?? (root as Record<string, unknown>).entry ?? []; const items = Array.isArray(raw) ? raw : [raw]; return items.filter(Boolean).map((item) => { const value = item as Record<string, unknown>; const title = String(value.title ?? "Source update"); const href = typeof value.link === "string" ? value.link : String((value.link as Record<string, unknown> | undefined)?.["@_href"] ?? baseUrl); const url = normalizeUrl(href, baseUrl); return { title, signalType: inferType(title), sourceUrl: url, canonicalUrl: url, externalRef: String(value.guid ?? value.id ?? url), postedAt: value.pubDate ? new Date(String(value.pubDate)).toISOString() : undefined, payload: { summary: value.description ?? value.summary } }; }); }
function parseHtml(html: string, baseUrl: string, metadata: Record<string, unknown>): ExtractedSignal[] { const $ = load(html); const selectors = (metadata.selectors ?? {}) as Record<string, string>; const itemSelector = selectors.item ?? "a[href]"; const results: ExtractedSignal[] = []; $(itemSelector).slice(0, 1000).each((_, element) => { const node = $(element); const title = (selectors.title ? node.find(selectors.title).first().text() : node.text()).replace(/\s+/g, " ").trim(); const href = selectors.url ? node.find(selectors.url).first().attr("href") : node.attr("href") ?? node.find("a[href]").first().attr("href"); const url = href ? normalizeUrl(href, baseUrl) : undefined; if (!title || !url || !/(intern|engineer|developer|job|fellow|program|career|event)/i.test(`${title} ${url}`)) return; results.push({ title, roleTitle: title, signalType: inferType(title), sourceUrl: url, canonicalUrl: url, externalRef: url, payload: { source: "html_selector" } }); }); return results; }
function csvRows(input: string) { const rows: string[][] = []; let row: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < input.length; index += 1) { const character = input[index]; if (character === '"') { if (quoted && input[index + 1] === '"') { value += '"'; index += 1; } else quoted = !quoted; } else if (character === "," && !quoted) { row.push(value); value = ""; } else if ((character === "\n" || character === "\r") && !quoted) { if (character === "\r" && input[index + 1] === "\n") index += 1; row.push(value); value = ""; if (row.some((cell) => cell.trim())) rows.push(row); row = []; } else value += character; } row.push(value); if (row.some((cell) => cell.trim())) rows.push(row); return rows; }
function isoDate(value: string | undefined) { if (!value) return undefined; const date = new Date(value); return Number.isNaN(date.getTime()) ? undefined : date.toISOString(); }
export function parseCsv(input: string, baseUrl: string): ExtractedSignal[] { const rows = csvRows(input); if (rows.length < 2) return []; const headers = rows[0].map((header) => header.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_")); return rows.slice(1, 1001).flatMap((row) => { const item = Object.fromEntries(headers.map((header, index) => [header, row[index]?.trim() ?? ""])); const title = item.title || item.role || item.position || item.job_title || item.name; const rawUrl = item.url || item.link || item.apply_url || item.application_url || item.job_url; const url = rawUrl ? normalizeUrl(rawUrl, baseUrl) : undefined; if (!title || !/(intern|engineer|developer|job|fellow|program|career|event)/i.test(`${title} ${url ?? ""}`)) return []; return [{ title, roleTitle: title, companyName: item.company || item.organization || undefined, location: item.location || undefined, signalType: inferType(title), opportunityType: inferType(title) === "internship_post" ? "internship" as const : "job" as const, sourceUrl: url ?? baseUrl, canonicalUrl: url, externalRef: item.id || url || `${title}:${item.company ?? ""}`, postedAt: isoDate(item.posted_at), deadlineAt: isoDate(item.deadline), payload: item }]; }); }
function atsSignals(items: Array<Record<string, unknown>>, baseUrl: string): ExtractedSignal[] { return items.map((item) => { const title = String(item.title ?? item.name ?? "Job opportunity"); const url = normalizeUrl(String(item.absolute_url ?? item.hostedUrl ?? item.jobUrl ?? item.applyUrl ?? baseUrl), baseUrl); const locationValue = item.location as Record<string, unknown> | string | undefined; const location = typeof locationValue === "string" ? locationValue : String(locationValue?.name ?? item.locationName ?? ""); return { title, roleTitle: title, companyName: String(item.companyName ?? "") || undefined, location: location || undefined, signalType: inferType(title), opportunityType: inferType(title) === "internship_post" ? "internship" : "job", sourceUrl: url, canonicalUrl: url, externalRef: String(item.id ?? item.jobId ?? url), postedAt: typeof item.updatedAt === "string" ? item.updatedAt : undefined, payload: item }; }); }

export async function runSourceAdapter(monitor: SourceMonitorJob) {
  const source = await assertPublicUrl(monitor.url); let fetchUrl = source.toString(); let adapter = String(monitor.metadata.adapterType ?? monitor.source_type);
  if (typeof monitor.metadata.fetchUrl === "string") fetchUrl = monitor.metadata.fetchUrl;
  if (monitor.source_type === "github_repo") { const parts = source.pathname.split("/").filter(Boolean); fetchUrl = `https://raw.githubusercontent.com/${parts[0]}/${parts[1]}/HEAD/README.md`; adapter = "github_markdown"; }
  if (monitor.source_type === "greenhouse_board") { const token = source.pathname.split("/").filter(Boolean).at(-1)!; fetchUrl = `https://boards-api.greenhouse.io/v1/boards/${token}/jobs?content=true`; adapter = "greenhouse"; }
  if (monitor.source_type === "lever_board") { const token = source.pathname.split("/").filter(Boolean).at(-1)!; fetchUrl = `https://api.lever.co/v0/postings/${token}?mode=json`; adapter = "lever"; }
  if (monitor.source_type === "ashby_board") { const token = source.pathname.split("/").filter(Boolean).at(-1)!; fetchUrl = `https://api.ashbyhq.com/posting-api/job-board/${token}`; adapter = "ashby"; }
  const { body, contentType, finalUrl } = await fetchText(fetchUrl); let signals: ExtractedSignal[];
  if (adapter === "github_markdown") signals = parseGitHubMarkdown(body, monitor.url);
  else if (adapter === "csv" || /csv/.test(contentType)) signals = parseCsv(body, monitor.url);
  else if (adapter === "greenhouse") signals = atsSignals((JSON.parse(body) as { jobs: Array<Record<string, unknown>> }).jobs ?? [], monitor.url);
  else if (adapter === "lever") signals = atsSignals(JSON.parse(body) as Array<Record<string, unknown>>, monitor.url);
  else if (adapter === "ashby") signals = atsSignals((JSON.parse(body) as { jobs: Array<Record<string, unknown>> }).jobs ?? [], monitor.url);
  else if (adapter === "rss" || /xml/.test(contentType) || monitor.source_type === "newsletter") signals = parseRss(body, monitor.url);
  else if (adapter === "json" || /json/.test(contentType)) { const parsed = JSON.parse(body) as unknown; const items = Array.isArray(parsed) ? parsed : (parsed as { jobs?: Array<Record<string, unknown>>; results?: Array<Record<string, unknown>> }).jobs ?? (parsed as { results?: Array<Record<string, unknown>> }).results ?? []; signals = atsSignals(items as Array<Record<string, unknown>>, monitor.url); }
  else signals = parseHtml(body, monitor.url, monitor.metadata);
  return { status: signals.length ? "success" as const : "no_change" as const, signals, parserVersion: `builtin-${adapter}-1`, evidence: { fetchedUrl: finalUrl, contentType, bytes: Buffer.byteLength(body), adapter } };
}
