import type { Application, Goal, SourceMonitor, Task } from "./schemas";

const now = new Date().toISOString();

export const demoGoals: Goal[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    objectType: "goal",
    title: "Secure a SWE internship for the next recruiting cycle",
    status: "active",
    labels: ["swe", "internship"],
    relatedGoalIds: [],
    relatedApplicationIds: [],
    relatedOpportunityIds: [],
    relatedContactIds: [],
    relatedEventIds: [],
    evidenceIds: [],
    createdBy: "user",
    updatedBy: "user",
    createdAt: now,
    updatedAt: now,
    horizon: "1_year",
    track: "swe",
    allocationPercent: 70,
    rationale: "Internship application season is the active hedge toward FDE.",
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    objectType: "goal",
    title: "Keep entrepreneurship moving without crowding out recruiting",
    status: "active",
    labels: ["entrepreneurship"],
    relatedGoalIds: [],
    relatedApplicationIds: [],
    relatedOpportunityIds: [],
    relatedContactIds: [],
    relatedEventIds: [],
    evidenceIds: [],
    createdBy: "user",
    updatedBy: "user",
    createdAt: now,
    updatedAt: now,
    horizon: "90_day",
    track: "entrepreneurship",
    allocationPercent: 20,
    rationale: "Maintain momentum while SWE applications are higher priority.",
  },
];

export const demoTasks: Task[] = [
  {
    id: "33333333-3333-4333-8333-333333333333",
    objectType: "task",
    title: "Set up two durable internship source monitors",
    status: "todo",
    labels: ["source setup", "job app"],
    priority: 90,
    dueAt: now,
    relatedGoalIds: [demoGoals[0].id],
    relatedApplicationIds: [],
    relatedOpportunityIds: [],
    relatedContactIds: [],
    relatedEventIds: [],
    evidenceIds: [],
    createdBy: "agent",
    updatedBy: "agent",
    createdAt: now,
    updatedAt: now,
    taskType: "source_setup",
    effort: "medium",
    urgency: "high",
    energy: "medium",
    source: "agent",
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    objectType: "task",
    title: "Draft baseline SWE resume variant in LaTeX",
    status: "todo",
    labels: ["resume"],
    priority: 80,
    relatedGoalIds: [demoGoals[0].id],
    relatedApplicationIds: [],
    relatedOpportunityIds: [],
    relatedContactIds: [],
    relatedEventIds: [],
    evidenceIds: [],
    createdBy: "agent",
    updatedBy: "agent",
    createdAt: now,
    updatedAt: now,
    taskType: "resume",
    effort: "large",
    urgency: "normal",
    energy: "high",
    source: "agent",
  },
];

export const demoApplications: Application[] = [
  {
    id: "55555555-5555-4555-8555-555555555555",
    objectType: "application",
    title: "Example SWE Internship",
    status: "found",
    labels: ["job app", "swe"],
    priority: 75,
    relatedGoalIds: [demoGoals[0].id],
    relatedApplicationIds: [],
    relatedOpportunityIds: [],
    relatedContactIds: [],
    relatedEventIds: [],
    evidenceIds: [],
    createdBy: "agent",
    updatedBy: "agent",
    createdAt: now,
    updatedAt: now,
    opportunityId: "66666666-6666-4666-8666-666666666666",
    statusCheckPolicy: "scheduled_agent",
    nextStatusCheckAt: now,
  },
];

export const demoSourceMonitors: SourceMonitor[] = [
  {
    id: "77777777-7777-4777-8777-777777777777",
    objectType: "source_monitor",
    title: "GitHub internship list monitor",
    status: "proposed",
    labels: ["github", "job app"],
    priority: 85,
    relatedGoalIds: [demoGoals[0].id],
    relatedApplicationIds: [],
    relatedOpportunityIds: [],
    relatedContactIds: [],
    relatedEventIds: [],
    evidenceIds: [],
    createdBy: "agent",
    updatedBy: "agent",
    createdAt: now,
    updatedAt: now,
    sourceType: "github_repo",
    url: "https://github.com/example/internships",
    fetchStrategy: "git_pull",
    schedule: "every_6_hours",
    requiresAuth: false,
    browserUseEnabled: false,
    lastSeenCursor: undefined,
    lastSeenHash: undefined,
    sourceRationale: "Structured public list suitable for deterministic GitHub parsing once activated.",
    evaluation: {},
    relatedCompanyIds: [],
  },
];
